### ISSUE TITLE
Health not loading properly for playable characters

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4Life/Thirdym#12]
characters that are meant to have more than 500 hp doesnt have more than 500 hp

![health glitch](https://user-images.githubusercontent.com/90115354/132109724-bad2299a-1088-471a-ac08-e3744ff6273f.png)
![part 2](https://user-images.githubusercontent.com/90115354/132109727-7754f975-9da0-4d4e-9659-94d1fbce8889.png)
![part 3](https://user-images.githubusercontent.com/90115354/132109729-b0e5f6ea-d7c4-4943-b900-292c17cce0ea.png)

**Comment by Gann4** [comment]
This is true and i'll check that, thanks for spotting it!
Make sure to provide comparisons too, for example taking screenshots on character customization plus screenshots ingame.
