### ISSUE TITLE
Manually spawned NPCs not reacting

### ISSUE THREAD

**Issue by imcreativeaboutusernames** [Gann4Life/Thirdym#13]
manually spawned npcs does not react to your presence even if your an enemy
![react](https://user-images.githubusercontent.com/90115354/132110183-4c90b233-3e50-4106-902f-a6e4bfa69c0d.png)

**Comment by imcreativeaboutusernames** [comment]
Manually spawning too many NPCs can also make them way affected by the bullet knockback

**Comment by Gann4Life** [comment]
> Manually spawning too many NPCs can also make them way affected by the bullet knockback

This can be a code issue regarding perfomance (longer render time per frame might make bullets hit harder).
