### ISSUE TITLE
Defilibrator causes mental dysfunction

### ISSUE THREAD

**Issue by Misty125** [Gann4Life/Thirdym#21]
After you get rape- i mean, get shot and get down due to low HP, you usually will use an defi on yourself, but after you get up, you dont have control of direction, pressing any button to walk (WASD) will make your character walk to the direction that he is looking, it also can naturally change direction like he has no control to where he is going, a similar effect happens when you pause the game. You can still change the direction of it by aiming, also walk to any direction normaly while doing so, but when you stop aiming, the bug still there.

**Comment by Gann4Life** [comment]
Looks like an issue related to the locomotion and HP system logic, i will take a look when i'm able to touch my computer again.
